apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: skaffold-config
build:
  local: {}
  artifacts:
    - image: elastic/apm-k8s-attacher
      docker:
        dockerfile: "Dockerfile"
deploy:
  helm:
    releases:
      - name: apm-attacher
        chartPath: apm-attacher
        artifactOverrides:
          image: elastic/apm-k8s-attacher
        imageStrategy:
          helm: {}
        namespace: elastic-apm
        createNamespace: true
        valuesFiles:
          - custom.yaml
        setValues:
          # Image is pushed to local repository only; do not check for image
          # presence in external repo.
          image.pullPolicy: IfNotPresent
