# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy everything else and build app
COPY . .
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app ./
ENV ELASTIC_APM_PROFILER_LOG_TARGETS=stdout;file
ENV ELASTIC_APM_PROFILER_LOG=trace
ENTRYPOINT ["dotnet", "dotnetapp.dll"]