image:
  repository: docker.elastic.co/observability/apm-attacher
  tag: "v1.1.0"
  pullPolicy: Always
  pullSecrets: []

certFile: cert.pem
keyFile: key.pem
apm:
  namespaces:
    - default
  secret_token:
  api_key:

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}

webhookConfig:
  agents:
    java:
      image: docker.elastic.co/observability/apm-agent-java:latest
      artifact: "/usr/agent/elastic-apm-agent.jar"
      environment:
        JAVA_TOOL_OPTIONS: "-javaagent:/elastic/apm/agent/elastic-apm-agent.jar"
    nodejs:
      image: docker.elastic.co/observability/apm-agent-nodejs:latest
      artifact: "/opt/nodejs/node_modules/elastic-apm-node"
      environment:
        NODE_OPTIONS: "-r /elastic/apm/agent/elastic-apm-node/start"
    dotnet:
      image: docker.elastic.co/observability/apm-agent-dotnet:latest
      artifact: "/usr/agent/apm-dotnet-agent"
      environment:
        CORECLR_ENABLE_PROFILING: "1"
        CORECLR_PROFILER: "{FA65FE15-F085-4681-9B20-95E04F6C03CC}"
        CORECLR_PROFILER_PATH: "/elastic/apm/agent/apm-dotnet-agent/libelastic_apm_profiler.so"
        ELASTIC_APM_PROFILER_HOME: "/elastic/apm/agent/apm-dotnet-agent"
        ELASTIC_APM_PROFILER_INTEGRATIONS: "/elastic/apm/agent/apm-dotnet-agent/integrations.yml"
